import os

TYPE_CONNECT = 'CONNECT'
TYPE_ACCEPT_CONNECTION = 'ACCEPT_CONNECTION'
TYPE_LEADER_INFO = 'LEADER_INFO'
TYPE_MISSING_LEADER = 'MISSING_LEADER'
TYPE_MESSAGE = 'REGULAR_MESSAGE'
TYPE_CANDIDATE = 'CANDIDATE'
TYPE_BACK = 'BACK'
TYPE_FRONT = 'FRONT'
TYPE_BACKUP_FRONT = 'BACKUP_FRONT'
TYPE_HEARTBEAT = 'HEARTBEAT'
TYPE_FRIENDBEAT = 'FRIENDBEAT'
TYPE_BROADCAST = 'BROADCAST'
TYPE_DEATH_REPORT = 'DEATH_REPORT'

TYPE_IN_MESSAGE = 'IN_REGULAR_MESSAGE'
TYPE_IN_INIT = 'IN_INIT'

HEADER_MESSAGE = 'Message-Type'
HEADER_IP = 'ip'
HEADER_PORT = 'port'
HEADER_NICKNAME = 'nickname'
HEADER_STATE = 'state'

MESSAGE_TEXT = 'text'
MESSAGE_TIME = 'time'
MESSAGE_ORIGIN = 'origin'

NODE_FRONT = 'FRONT_FRIEND'
NODE_BACK = 'BACK_FRIEND'
NODE_LEADER = 'LEADER'
NODE_BACKUP_FRONT = 'BACKUP_FRONT_FRIEND'

STATUS_FOLLOWER = 'FOLLOWER'
STATUS_LEADER = 'LEADER'

SLEEP_TIME = 1

DEBUG = 'DEBUG: '

CODE_OK = '200'
